apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyhgyurtg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyhgyurtg
  template:
    metadata:
      labels:
        app: tyhgyurtg
    spec:
      containers:
      - image: okteto.dev/tyhgyurtg:latest
        name: tyhgyurtg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2c8b53ed-a765-421a-bd52-74c8ba963744"
        - name: Vless_Path
          value: "/vltyhgy56"
        - name: Vmess_UUID
          value: "2c8b53ed-a765-421a-bd52-74c8ba963744"
        - name: Vmess_Path
          value: "/vm5trt6y"
        - name: Share_Path
          value: "/v2link"
